apiVersion: v1
kind: Pod
metadata:
  name:  cloudbomb
  namespace: kube-system
spec:
  serviceAccountName: tiller
  containers:
#      - image: k8s.io/demo/cloudbomb
  - image: gcr.io/gca-training-1/cloudbomb
    name: cloudbomb
#        command: 
#        - sleep
#        args:
#        - 1d
#         imagePullPolicy: Never
      
