#!/bin/bash

iptables-restore << EOT
# Generated by iptables-save v1.4.21 on Sat Nov  7 15:11:33 2015
*nat
:PREROUTING ACCEPT [5759:527435]
:INPUT ACCEPT [5470:455816]
:OUTPUT ACCEPT [8272:1062079]
:POSTROUTING ACCEPT [8272:1062079]
COMMIT
# Completed on Sat Nov  7 15:11:33 2015
# Generated by iptables-save v1.4.21 on Sat Nov  7 15:11:33 2015
*mangle
:PREROUTING ACCEPT [42680:22060825]
:INPUT ACCEPT [42397:21987129]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [36048:6631147]
:POSTROUTING ACCEPT [36096:6637291]
COMMIT
# Completed on Sat Nov  7 15:11:33 2015
# Generated by iptables-save v1.4.21 on Sat Nov  7 15:11:33 2015
*filter
:INPUT ACCEPT [873:178921]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [836:265574]
-A INPUT -i eth0 -p udp -m udp --dport 6881 -j DROP
-A INPUT -i eth0 -p tcp -m tcp --dport 6881 -j DROP
-A INPUT -i tun0 -p tcp -m tcp --dport 4711 -j DROP
-A INPUT -i tun0 -p tcp -m tcp --dport 8080 -j DROP
COMMIT
# Completed on Sat Nov  7 15:11:33 2015
EOT

PROTO=${PROTO:-tcp443}
COUNTRY=${COUNTRY:-Denmark}
COUNTRY_ID=$(curl --silent "https://api.nordvpn.com/v1/servers/countries" | jq --raw-output '.[] | select(.name == "'${COUNTRY}'") | .id ')
SERVER=$(curl --silent "https://api.nordvpn.com/v1/servers/recommendations?filters\[servers_groups\]&filters\[country_id\]=${COUNTRY_ID}&limit=1" \
        | jq --raw-output '.[].hostname')
curl -s https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/${SERVER}.${PROTO}.ovpn  \
 | sed 's+auth-user-pass+& /etc/vpn/passwd.conf+' > /tmp/server.ovpn

exec /usr/sbin/openvpn  --config /tmp/server.ovpn

