apiVersion: v1
kind: Pod
metadata:
  name: w10-zombie
  labels:
    app: zombie
spec:
  containers:
    - name: zombie
      image: qemu
      imagePullPolicy: Never
      env:
      - name: KEYBOARD
        value: de
      volumeMounts:
      - name: qcow
        mountPath: /disc.qcow
        #      securityContext:
        # privileged: true
    - name: novnc
      image: dougw/novnc
      ports:
      - name: web 
        containerPort: 8081
  volumes:
  - name: qcow
    hostPath:
      path: "/home/thomas/import/Microsoft Windows NT 4.0 Enterprise Server (4.00.1381.1)/disk.qcow"
      type: File 

