apiVersion: v1
kind: Service
metadata:
  name: w10-zombie
spec:
  selector:
    app: zombie
  ports:
    - name: vnc 
      protocol: TCP
      port: 5900
      targetPort: 5900
    - name: novnc
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32081
  type: LoadBalancer
